modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL="https://github.com/JamCoreModding/bulk-storage-crates/issues"

[[mods]]
modId = "bulk_storage_crates"
version = "${version}"
displayName = "Bulk Storage Crates"
displayURL="https://github.com/JamCoreModding/bulk-storage-crates"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
Adds transportable crates for all your bulk storage needs
'''

[[dependencies.bulk_storage_crates]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bulk_storage_crates]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bulk_storage_crates]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bulk_storage_crates]]
modId = "jamlib"
type = "required"
versionRange = "[${jamlib_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "bulk_storage_crates.mixins.json"
